import { MigrationInterface, QueryRunner } from "typeorm";

export class AddIsArchivedToUsers1776382657122 implements MigrationInterface {
    name = 'AddIsArchivedToUsers1776382657122'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`isArchived\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP FOREIGN KEY \`FK_fe8e7d37475de7eb2f8f83a6da0\``);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`restaurantId\` \`restaurantId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`menu_items\` DROP FOREIGN KEY \`FK_d56e5ccc298e8bf721f75a7eb96\``);
        await queryRunner.query(`ALTER TABLE \`menu_items\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`menu_items\` CHANGE \`imageUrl\` \`imageUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`menu_items\` CHANGE \`badgeLabel\` \`badgeLabel\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`menu_items\` CHANGE \`badgeColor\` \`badgeColor\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`menu_items\` CHANGE \`prepTime\` \`prepTime\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`menu_items\` CHANGE \`calories\` \`calories\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`menu_items\` CHANGE \`allergens\` \`allergens\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`menu_items\` CHANGE \`dietaryLabels\` \`dietaryLabels\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`menu_items\` CHANGE \`availableDays\` \`availableDays\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`menu_items\` CHANGE \`subcategoryName\` \`subcategoryName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`menu_items\` CHANGE \`categoryId\` \`categoryId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_f1d359a55923bb45b057fbdab0d\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_d8453d5a71e525d9b406c35aab8\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`orderId\` \`orderId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`menuItemId\` \`menuItemId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_2312cd07a04f50ba29d76c9564e\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_2a7fdd7af437285a3ef0fc8b64f\``);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`orderNumber\` \`orderNumber\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`customerName\` \`customerName\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`stripeSessionId\` \`stripeSessionId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`restaurantId\` \`restaurantId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`tableId\` \`tableId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`tables\` DROP FOREIGN KEY \`FK_94e0a6541322cecd437cd841701\``);
        await queryRunner.query(`ALTER TABLE \`tables\` CHANGE \`restaurantId\` \`restaurantId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`subscriptions\` DROP FOREIGN KEY \`FK_8efcb4b7bc1122ed19df1897d22\``);
        await queryRunner.query(`ALTER TABLE \`subscriptions\` CHANGE \`currentPeriodEnd\` \`currentPeriodEnd\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`subscriptions\` CHANGE \`restaurantId\` \`restaurantId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`restaurants\` CHANGE \`address\` \`address\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`restaurants\` CHANGE \`phoneNumber\` \`phoneNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`restaurants\` CHANGE \`logoUrl\` \`logoUrl\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`restaurants\` CHANGE \`stripeAccountId\` \`stripeAccountId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_4ca7f2f579cda8a6158c7fc1650\``);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`restaurantId\` \`restaurantId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`plans\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`plans\` CHANGE \`stripePriceId\` \`stripePriceId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`plans\` DROP COLUMN \`features\``);
        await queryRunner.query(`ALTER TABLE \`plans\` ADD \`features\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`staff_members\` DROP FOREIGN KEY \`FK_e360dda42b3876dc5a856d44ca4\``);
        await queryRunner.query(`ALTER TABLE \`staff_members\` DROP FOREIGN KEY \`FK_b87f635a2032acebd0a74246081\``);
        await queryRunner.query(`ALTER TABLE \`staff_members\` CHANGE \`phoneNumber\` \`phoneNumber\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`staff_members\` CHANGE \`position\` \`position\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`staff_members\` CHANGE \`userId\` \`userId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`staff_members\` CHANGE \`restaurantId\` \`restaurantId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`restaurant_settings\` DROP FOREIGN KEY \`FK_0fbfc0e256a87208b9e3083628e\``);
        await queryRunner.query(`ALTER TABLE \`restaurant_settings\` CHANGE \`restaurantId\` \`restaurantId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` DROP FOREIGN KEY \`FK_f290a56fcecb987c14c68414056\``);
        await queryRunner.query(`ALTER TABLE \`reservations\` DROP FOREIGN KEY \`FK_42ee40914a466cb26141c81e878\``);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`customerEmail\` \`customerEmail\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`notes\` \`notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`restaurantId\` \`restaurantId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`tableId\` \`tableId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP FOREIGN KEY \`FK_af929a5f2a400fdb6913b4967e1\``);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`stripePaymentIntentId\` \`stripePaymentIntentId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`stripeSessionId\` \`stripeSessionId\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`orderId\` \`orderId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`menu_item_options\` DROP FOREIGN KEY \`FK_7615f34e2b9554c8d9fe0062a79\``);
        await queryRunner.query(`ALTER TABLE \`menu_item_options\` CHANGE \`menuItemId\` \`menuItemId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`menu_categories\` DROP FOREIGN KEY \`FK_99fac3bd8f4554721f954244df0\``);
        await queryRunner.query(`ALTER TABLE \`menu_categories\` CHANGE \`description\` \`description\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`menu_categories\` CHANGE \`restaurantId\` \`restaurantId\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD CONSTRAINT \`FK_fe8e7d37475de7eb2f8f83a6da0\` FOREIGN KEY (\`restaurantId\`) REFERENCES \`restaurants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`menu_items\` ADD CONSTRAINT \`FK_d56e5ccc298e8bf721f75a7eb96\` FOREIGN KEY (\`categoryId\`) REFERENCES \`categories\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_f1d359a55923bb45b057fbdab0d\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_d8453d5a71e525d9b406c35aab8\` FOREIGN KEY (\`menuItemId\`) REFERENCES \`menu_items\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_2312cd07a04f50ba29d76c9564e\` FOREIGN KEY (\`restaurantId\`) REFERENCES \`restaurants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_2a7fdd7af437285a3ef0fc8b64f\` FOREIGN KEY (\`tableId\`) REFERENCES \`tables\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tables\` ADD CONSTRAINT \`FK_94e0a6541322cecd437cd841701\` FOREIGN KEY (\`restaurantId\`) REFERENCES \`restaurants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`subscriptions\` ADD CONSTRAINT \`FK_8efcb4b7bc1122ed19df1897d22\` FOREIGN KEY (\`restaurantId\`) REFERENCES \`restaurants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_4ca7f2f579cda8a6158c7fc1650\` FOREIGN KEY (\`restaurantId\`) REFERENCES \`restaurants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`staff_members\` ADD CONSTRAINT \`FK_e360dda42b3876dc5a856d44ca4\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`staff_members\` ADD CONSTRAINT \`FK_b87f635a2032acebd0a74246081\` FOREIGN KEY (\`restaurantId\`) REFERENCES \`restaurants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`restaurant_settings\` ADD CONSTRAINT \`FK_0fbfc0e256a87208b9e3083628e\` FOREIGN KEY (\`restaurantId\`) REFERENCES \`restaurants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reservations\` ADD CONSTRAINT \`FK_f290a56fcecb987c14c68414056\` FOREIGN KEY (\`restaurantId\`) REFERENCES \`restaurants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reservations\` ADD CONSTRAINT \`FK_42ee40914a466cb26141c81e878\` FOREIGN KEY (\`tableId\`) REFERENCES \`tables\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD CONSTRAINT \`FK_af929a5f2a400fdb6913b4967e1\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`menu_item_options\` ADD CONSTRAINT \`FK_7615f34e2b9554c8d9fe0062a79\` FOREIGN KEY (\`menuItemId\`) REFERENCES \`menu_items\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`menu_categories\` ADD CONSTRAINT \`FK_99fac3bd8f4554721f954244df0\` FOREIGN KEY (\`restaurantId\`) REFERENCES \`restaurants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`menu_categories\` DROP FOREIGN KEY \`FK_99fac3bd8f4554721f954244df0\``);
        await queryRunner.query(`ALTER TABLE \`menu_item_options\` DROP FOREIGN KEY \`FK_7615f34e2b9554c8d9fe0062a79\``);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP FOREIGN KEY \`FK_af929a5f2a400fdb6913b4967e1\``);
        await queryRunner.query(`ALTER TABLE \`reservations\` DROP FOREIGN KEY \`FK_42ee40914a466cb26141c81e878\``);
        await queryRunner.query(`ALTER TABLE \`reservations\` DROP FOREIGN KEY \`FK_f290a56fcecb987c14c68414056\``);
        await queryRunner.query(`ALTER TABLE \`restaurant_settings\` DROP FOREIGN KEY \`FK_0fbfc0e256a87208b9e3083628e\``);
        await queryRunner.query(`ALTER TABLE \`staff_members\` DROP FOREIGN KEY \`FK_b87f635a2032acebd0a74246081\``);
        await queryRunner.query(`ALTER TABLE \`staff_members\` DROP FOREIGN KEY \`FK_e360dda42b3876dc5a856d44ca4\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_4ca7f2f579cda8a6158c7fc1650\``);
        await queryRunner.query(`ALTER TABLE \`subscriptions\` DROP FOREIGN KEY \`FK_8efcb4b7bc1122ed19df1897d22\``);
        await queryRunner.query(`ALTER TABLE \`tables\` DROP FOREIGN KEY \`FK_94e0a6541322cecd437cd841701\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_2a7fdd7af437285a3ef0fc8b64f\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_2312cd07a04f50ba29d76c9564e\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_d8453d5a71e525d9b406c35aab8\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_f1d359a55923bb45b057fbdab0d\``);
        await queryRunner.query(`ALTER TABLE \`menu_items\` DROP FOREIGN KEY \`FK_d56e5ccc298e8bf721f75a7eb96\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP FOREIGN KEY \`FK_fe8e7d37475de7eb2f8f83a6da0\``);
        await queryRunner.query(`ALTER TABLE \`menu_categories\` CHANGE \`restaurantId\` \`restaurantId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`menu_categories\` CHANGE \`description\` \`description\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`menu_categories\` ADD CONSTRAINT \`FK_99fac3bd8f4554721f954244df0\` FOREIGN KEY (\`restaurantId\`) REFERENCES \`restaurants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`menu_item_options\` CHANGE \`menuItemId\` \`menuItemId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`menu_item_options\` ADD CONSTRAINT \`FK_7615f34e2b9554c8d9fe0062a79\` FOREIGN KEY (\`menuItemId\`) REFERENCES \`menu_items\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`orderId\` \`orderId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`stripeSessionId\` \`stripeSessionId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` CHANGE \`stripePaymentIntentId\` \`stripePaymentIntentId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD CONSTRAINT \`FK_af929a5f2a400fdb6913b4967e1\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`tableId\` \`tableId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`restaurantId\` \`restaurantId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`notes\` \`notes\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` CHANGE \`customerEmail\` \`customerEmail\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`reservations\` ADD CONSTRAINT \`FK_42ee40914a466cb26141c81e878\` FOREIGN KEY (\`tableId\`) REFERENCES \`tables\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reservations\` ADD CONSTRAINT \`FK_f290a56fcecb987c14c68414056\` FOREIGN KEY (\`restaurantId\`) REFERENCES \`restaurants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`restaurant_settings\` CHANGE \`restaurantId\` \`restaurantId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`restaurant_settings\` ADD CONSTRAINT \`FK_0fbfc0e256a87208b9e3083628e\` FOREIGN KEY (\`restaurantId\`) REFERENCES \`restaurants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`staff_members\` CHANGE \`restaurantId\` \`restaurantId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`staff_members\` CHANGE \`userId\` \`userId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`staff_members\` CHANGE \`position\` \`position\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`staff_members\` CHANGE \`phoneNumber\` \`phoneNumber\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`staff_members\` ADD CONSTRAINT \`FK_b87f635a2032acebd0a74246081\` FOREIGN KEY (\`restaurantId\`) REFERENCES \`restaurants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`staff_members\` ADD CONSTRAINT \`FK_e360dda42b3876dc5a856d44ca4\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`plans\` DROP COLUMN \`features\``);
        await queryRunner.query(`ALTER TABLE \`plans\` ADD \`features\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`plans\` CHANGE \`stripePriceId\` \`stripePriceId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`plans\` CHANGE \`description\` \`description\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`restaurantId\` \`restaurantId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_4ca7f2f579cda8a6158c7fc1650\` FOREIGN KEY (\`restaurantId\`) REFERENCES \`restaurants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`restaurants\` CHANGE \`stripeAccountId\` \`stripeAccountId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`restaurants\` CHANGE \`logoUrl\` \`logoUrl\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`restaurants\` CHANGE \`phoneNumber\` \`phoneNumber\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`restaurants\` CHANGE \`address\` \`address\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`subscriptions\` CHANGE \`restaurantId\` \`restaurantId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`subscriptions\` CHANGE \`currentPeriodEnd\` \`currentPeriodEnd\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`subscriptions\` ADD CONSTRAINT \`FK_8efcb4b7bc1122ed19df1897d22\` FOREIGN KEY (\`restaurantId\`) REFERENCES \`restaurants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tables\` CHANGE \`restaurantId\` \`restaurantId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`tables\` ADD CONSTRAINT \`FK_94e0a6541322cecd437cd841701\` FOREIGN KEY (\`restaurantId\`) REFERENCES \`restaurants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`tableId\` \`tableId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`restaurantId\` \`restaurantId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`stripeSessionId\` \`stripeSessionId\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`customerName\` \`customerName\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`orderNumber\` \`orderNumber\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_2a7fdd7af437285a3ef0fc8b64f\` FOREIGN KEY (\`tableId\`) REFERENCES \`tables\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_2312cd07a04f50ba29d76c9564e\` FOREIGN KEY (\`restaurantId\`) REFERENCES \`restaurants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`menuItemId\` \`menuItemId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`orderId\` \`orderId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_d8453d5a71e525d9b406c35aab8\` FOREIGN KEY (\`menuItemId\`) REFERENCES \`menu_items\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_f1d359a55923bb45b057fbdab0d\` FOREIGN KEY (\`orderId\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`menu_items\` CHANGE \`categoryId\` \`categoryId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`menu_items\` CHANGE \`subcategoryName\` \`subcategoryName\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`menu_items\` CHANGE \`availableDays\` \`availableDays\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`menu_items\` CHANGE \`dietaryLabels\` \`dietaryLabels\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`menu_items\` CHANGE \`allergens\` \`allergens\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`menu_items\` CHANGE \`calories\` \`calories\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`menu_items\` CHANGE \`prepTime\` \`prepTime\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`menu_items\` CHANGE \`badgeColor\` \`badgeColor\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`menu_items\` CHANGE \`badgeLabel\` \`badgeLabel\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`menu_items\` CHANGE \`imageUrl\` \`imageUrl\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`menu_items\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`menu_items\` ADD CONSTRAINT \`FK_d56e5ccc298e8bf721f75a7eb96\` FOREIGN KEY (\`categoryId\`) REFERENCES \`categories\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`restaurantId\` \`restaurantId\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD CONSTRAINT \`FK_fe8e7d37475de7eb2f8f83a6da0\` FOREIGN KEY (\`restaurantId\`) REFERENCES \`restaurants\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`isArchived\``);
    }

}
